workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install Project Dependencies
        script: npm install
      - name: Run Build Script
        script: |
          chmod +x ./build-codemagic.sh
          ./build-codemagic.sh
    artifacts:
      - "**/*.ipa"
      - build/ios/ipa/*.ipa
