# iOS Podfile for WhatsApp AI Replier
# Generated for Expo SDK 51

platform :ios, '13.4'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/expo/scripts/autolinking'

target 'WhatsAppAIReplier' do
  use_expo_modules!
  use_frameworks!

  post_install do |installer|
    react_native_post_install(installer)

    # Fix iOS build settings for background location
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  end
end